// Compiles a dart2wasm-generated main module from `source` which can then
// instantiatable via the `instantiate` method.
//
// `source` needs to be a `Response` object (or promise thereof) e.g. created
// via the `fetch()` JS API.
export async function compileStreaming(source) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(
      await WebAssembly.compileStreaming(source, builtins), builtins);
}

// Compiles a dart2wasm-generated wasm modules from `bytes` which is then
// instantiatable via the `instantiate` method.
export async function compile(bytes) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(await WebAssembly.compile(bytes, builtins), builtins);
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export async function instantiate(modulePromise, importObjectPromise) {
  var moduleOrCompiledApp = await modulePromise;
  if (!(moduleOrCompiledApp instanceof CompiledApp)) {
    moduleOrCompiledApp = new CompiledApp(moduleOrCompiledApp);
  }
  const instantiatedApp = await moduleOrCompiledApp.instantiate(await importObjectPromise);
  return instantiatedApp.instantiatedModule;
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export const invoke = (moduleInstance, ...args) => {
  moduleInstance.exports.$invokeMain(args);
}

class CompiledApp {
  constructor(module, builtins) {
    this.module = module;
    this.builtins = builtins;
  }

  // The second argument is an options object containing:
  // `loadDeferredModule` is a JS function that takes a module name matching a
  //   wasm file produced by the dart2wasm compiler and returns the bytes to
  //   load the module. These bytes can be in either a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  // `loadDynamicModule` is a JS function that takes two string names matching,
  //   in order, a wasm file produced by the dart2wasm compiler during dynamic
  //   module compilation and a corresponding js file produced by the same
  //   compilation. It should return a JS Array containing 2 elements. The first
  //   should be the bytes for the wasm module in a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`. The second
  //   should be the result of using the JS 'import' API on the js file path.
  // `loadDeferredId` is a JS function that takes a string corresponding to a load
  //   ID generated by the compiler when 'load-ids' option is passed. Each load
  //   ID maps to one or more WASM modules produced by the compiler. This
  //   function should return an array of byte arrays corresponding to all the
  //   modules specified by that load ID. The arrays should be in a format
  //   supported by `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  async instantiate(additionalImports,
      {loadDeferredModule, loadDynamicModule, loadDeferredId} = {}) {
    let dartInstance;

    // Prints to the console
    function printToConsole(value) {
      if (typeof dartPrint == "function") {
        dartPrint(value);
        return;
      }
      if (typeof console == "object" && typeof console.log != "undefined") {
        console.log(value);
        return;
      }
      if (typeof print == "function") {
        print(value);
        return;
      }

      throw "Unable to print message: " + value;
    }

    // A special symbol attached to functions that wrap Dart functions.
    const jsWrappedDartFunctionSymbol = Symbol("JSWrappedDartFunction");

    function finalizeWrapper(dartFunction, wrapped) {
      wrapped.dartFunction = dartFunction;
      wrapped[jsWrappedDartFunctionSymbol] = true;
      return wrapped;
    }

    // Imports
    const dart2wasm = {
            _1: (decoder, codeUnits) => decoder.decode(codeUnits),
      _2: () => new TextDecoder("utf-8", {fatal: true}),
      _3: () => new TextDecoder("utf-8", {fatal: false}),
      _4: (s) => +s,
      _5: x0 => new Uint8Array(x0),
      _6: (x0,x1,x2) => x0.set(x1,x2),
      _7: (x0,x1) => x0.transferFromImageBitmap(x1),
      _9: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._9(f,arguments.length,x0) }),
      _10: x0 => new window.FinalizationRegistry(x0),
      _11: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _12: (x0,x1) => x0.unregister(x1),
      _13: (x0,x1,x2) => x0.slice(x1,x2),
      _14: (x0,x1) => x0.decode(x1),
      _15: (x0,x1) => x0.segment(x1),
      _16: () => new TextDecoder(),
      _18: x0 => x0.buffer,
      _19: x0 => x0.wasmMemory,
      _20: () => globalThis.window._flutter_skwasmInstance,
      _21: x0 => x0.rasterStartMilliseconds,
      _22: x0 => x0.rasterEndMilliseconds,
      _23: x0 => x0.imageBitmaps,
      _139: (x0,x1) => x0.appendChild(x1),
      _170: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _171: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _172: (x0,x1) => new OffscreenCanvas(x0,x1),
      _173: x0 => x0.remove(),
      _174: (x0,x1) => x0.append(x1),
      _176: x0 => x0.unlock(),
      _177: x0 => x0.getReader(),
      _178: (x0,x1) => x0.item(x1),
      _179: x0 => x0.next(),
      _180: x0 => x0.now(),
      _181: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._181(f,arguments.length,x0) }),
      _182: (x0,x1) => x0.addListener(x1),
      _183: (x0,x1) => x0.removeListener(x1),
      _184: (x0,x1) => x0.matchMedia(x1),
      _185: (x0,x1) => x0.revokeObjectURL(x1),
      _186: x0 => x0.close(),
      _187: (x0,x1,x2,x3,x4) => ({type: x0,data: x1,premultiplyAlpha: x2,colorSpaceConversion: x3,preferAnimation: x4}),
      _188: x0 => new window.ImageDecoder(x0),
      _189: (x0,x1) => ({frameIndex: x0,completeFramesOnly: x1}),
      _190: (x0,x1) => x0.decode(x1),
      _191: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._191(f,arguments.length,x0) }),
      _192: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _194: (x0,x1) => x0.getModifierState(x1),
      _195: x0 => x0.preventDefault(),
      _196: x0 => x0.stopPropagation(),
      _197: (x0,x1) => x0.removeProperty(x1),
      _198: (x0,x1) => x0.prepend(x1),
      _199: x0 => new Intl.Locale(x0),
      _200: (x0,x1) => x0.observe(x1),
      _201: x0 => x0.disconnect(),
      _202: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._202(f,arguments.length,x0) }),
      _203: (x0,x1) => x0.getAttribute(x1),
      _204: (x0,x1) => x0.contains(x1),
      _205: (x0,x1) => x0.querySelector(x1),
      _206: x0 => x0.blur(),
      _207: x0 => x0.hasFocus(),
      _208: (x0,x1) => x0.removeAttribute(x1),
      _209: (x0,x1,x2) => x0.insertBefore(x1,x2),
      _210: (x0,x1) => x0.hasAttribute(x1),
      _211: (x0,x1) => x0.getModifierState(x1),
      _212: (x0,x1) => x0.createTextNode(x1),
      _213: x0 => x0.getBoundingClientRect(),
      _214: (x0,x1) => x0.closest(x1),
      _651: x0 => new Uint8Array(x0),
      _655: () => globalThis.window.flutterConfiguration,
      _657: x0 => x0.assetBase,
      _662: x0 => x0.canvasKitMaximumSurfaces,
      _663: x0 => x0.debugShowSemanticsNodes,
      _664: x0 => x0.hostElement,
      _665: x0 => x0.multiViewEnabled,
      _666: x0 => x0.nonce,
      _668: x0 => x0.fontFallbackBaseUrl,
      _678: x0 => x0.console,
      _679: x0 => x0.devicePixelRatio,
      _680: x0 => x0.document,
      _681: x0 => x0.history,
      _682: x0 => x0.innerHeight,
      _683: x0 => x0.innerWidth,
      _684: x0 => x0.location,
      _685: x0 => x0.navigator,
      _686: x0 => x0.visualViewport,
      _687: x0 => x0.performance,
      _689: x0 => x0.URL,
      _691: (x0,x1) => x0.getComputedStyle(x1),
      _692: x0 => x0.screen,
      _693: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._693(f,arguments.length,x0) }),
      _694: (x0,x1) => x0.requestAnimationFrame(x1),
      _698: (x0,x1) => x0.warn(x1),
      _700: (x0,x1) => x0.debug(x1),
      _701: x0 => globalThis.parseFloat(x0),
      _702: () => globalThis.window,
      _703: () => globalThis.Intl,
      _704: () => globalThis.Symbol,
      _705: (x0,x1,x2,x3,x4) => globalThis.createImageBitmap(x0,x1,x2,x3,x4),
      _707: x0 => x0.clipboard,
      _708: x0 => x0.maxTouchPoints,
      _709: x0 => x0.vendor,
      _710: x0 => x0.language,
      _711: x0 => x0.platform,
      _712: x0 => x0.userAgent,
      _713: (x0,x1) => x0.vibrate(x1),
      _714: x0 => x0.languages,
      _715: x0 => x0.documentElement,
      _716: (x0,x1) => x0.querySelector(x1),
      _717: (x0,x1) => x0.querySelectorAll(x1),
      _719: (x0,x1) => x0.createElement(x1),
      _722: (x0,x1) => x0.createEvent(x1),
      _723: x0 => x0.activeElement,
      _726: x0 => x0.head,
      _727: x0 => x0.body,
      _728: (x0,x1) => { x0.title = x1 },
      _732: x0 => x0.visibilityState,
      _733: () => globalThis.document,
      _734: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._734(f,arguments.length,x0) }),
      _735: (x0,x1) => x0.dispatchEvent(x1),
      _743: x0 => x0.target,
      _745: x0 => x0.timeStamp,
      _746: x0 => x0.type,
      _748: (x0,x1,x2,x3) => x0.initEvent(x1,x2,x3),
      _755: x0 => x0.firstChild,
      _759: x0 => x0.parentElement,
      _761: (x0,x1) => { x0.textContent = x1 },
      _762: x0 => x0.parentNode,
      _763: x0 => x0.nextSibling,
      _764: (x0,x1) => x0.removeChild(x1),
      _765: x0 => x0.isConnected,
      _773: x0 => x0.clientHeight,
      _774: x0 => x0.clientWidth,
      _775: x0 => x0.offsetHeight,
      _776: x0 => x0.offsetWidth,
      _777: x0 => x0.id,
      _778: (x0,x1) => { x0.id = x1 },
      _781: (x0,x1) => { x0.spellcheck = x1 },
      _782: x0 => x0.tagName,
      _783: x0 => x0.style,
      _786: (x0,x1) => x0.querySelectorAll(x1),
      _787: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _788: (x0,x1) => { x0.tabIndex = x1 },
      _789: x0 => x0.tabIndex,
      _790: (x0,x1) => x0.focus(x1),
      _791: x0 => x0.scrollTop,
      _792: (x0,x1) => { x0.scrollTop = x1 },
      _793: x0 => x0.scrollLeft,
      _794: (x0,x1) => { x0.scrollLeft = x1 },
      _795: x0 => x0.classList,
      _797: (x0,x1) => { x0.className = x1 },
      _799: (x0,x1) => x0.getElementsByClassName(x1),
      _800: x0 => x0.click(),
      _801: (x0,x1) => x0.attachShadow(x1),
      _804: x0 => x0.computedStyleMap(),
      _805: (x0,x1) => x0.get(x1),
      _811: (x0,x1) => x0.getPropertyValue(x1),
      _812: (x0,x1,x2,x3) => x0.setProperty(x1,x2,x3),
      _813: x0 => x0.offsetLeft,
      _814: x0 => x0.offsetTop,
      _815: x0 => x0.offsetParent,
      _817: (x0,x1) => { x0.name = x1 },
      _818: x0 => x0.content,
      _819: (x0,x1) => { x0.content = x1 },
      _823: (x0,x1) => { x0.src = x1 },
      _824: x0 => x0.naturalWidth,
      _825: x0 => x0.naturalHeight,
      _829: (x0,x1) => { x0.crossOrigin = x1 },
      _831: (x0,x1) => { x0.decoding = x1 },
      _832: x0 => x0.decode(),
      _837: (x0,x1) => { x0.nonce = x1 },
      _841: (x0,x1) => { x0.width = x1 },
      _844: (x0,x1) => { x0.height = x1 },
      _847: (x0,x1) => x0.getContext(x1),
      _914: x0 => x0.width,
      _915: x0 => x0.height,
      _917: (x0,x1) => x0.fetch(x1),
      _918: x0 => x0.status,
      _920: x0 => x0.body,
      _921: x0 => x0.arrayBuffer(),
      _924: x0 => x0.read(),
      _925: x0 => x0.value,
      _926: x0 => x0.done,
      _933: x0 => x0.name,
      _934: x0 => x0.x,
      _935: x0 => x0.y,
      _938: x0 => x0.top,
      _939: x0 => x0.right,
      _940: x0 => x0.bottom,
      _941: x0 => x0.left,
      _951: x0 => x0.height,
      _952: x0 => x0.width,
      _953: x0 => x0.scale,
      _954: (x0,x1) => { x0.value = x1 },
      _957: (x0,x1) => { x0.placeholder = x1 },
      _959: (x0,x1) => { x0.name = x1 },
      _960: x0 => x0.selectionDirection,
      _961: x0 => x0.selectionStart,
      _962: x0 => x0.selectionEnd,
      _965: x0 => x0.value,
      _967: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _968: x0 => x0.readText(),
      _969: (x0,x1) => x0.writeText(x1),
      _971: x0 => x0.altKey,
      _972: x0 => x0.code,
      _973: x0 => x0.ctrlKey,
      _974: x0 => x0.key,
      _975: x0 => x0.keyCode,
      _976: x0 => x0.location,
      _977: x0 => x0.metaKey,
      _978: x0 => x0.repeat,
      _979: x0 => x0.shiftKey,
      _980: x0 => x0.isComposing,
      _982: x0 => x0.state,
      _983: (x0,x1) => x0.go(x1),
      _985: (x0,x1,x2,x3) => x0.pushState(x1,x2,x3),
      _986: (x0,x1,x2,x3) => x0.replaceState(x1,x2,x3),
      _987: x0 => x0.pathname,
      _988: x0 => x0.search,
      _989: x0 => x0.hash,
      _993: x0 => x0.state,
      _996: (x0,x1) => x0.createObjectURL(x1),
      _998: x0 => new Blob(x0),
      _1008: x0 => x0.matches,
      _1009: x0 => x0.matches,
      _1013: x0 => x0.relatedTarget,
      _1015: x0 => x0.clientX,
      _1016: x0 => x0.clientY,
      _1017: x0 => x0.offsetX,
      _1018: x0 => x0.offsetY,
      _1021: x0 => x0.button,
      _1022: x0 => x0.buttons,
      _1023: x0 => x0.ctrlKey,
      _1027: x0 => x0.pointerId,
      _1028: x0 => x0.pointerType,
      _1029: x0 => x0.pressure,
      _1030: x0 => x0.tiltX,
      _1031: x0 => x0.tiltY,
      _1032: x0 => x0.getCoalescedEvents(),
      _1035: x0 => x0.deltaX,
      _1036: x0 => x0.deltaY,
      _1037: x0 => x0.wheelDeltaX,
      _1038: x0 => x0.wheelDeltaY,
      _1039: x0 => x0.deltaMode,
      _1046: x0 => x0.changedTouches,
      _1049: x0 => x0.clientX,
      _1050: x0 => x0.clientY,
      _1053: x0 => x0.data,
      _1056: (x0,x1) => { x0.disabled = x1 },
      _1058: (x0,x1) => { x0.type = x1 },
      _1059: (x0,x1) => { x0.max = x1 },
      _1060: (x0,x1) => { x0.min = x1 },
      _1061: (x0,x1) => { x0.value = x1 },
      _1062: x0 => x0.value,
      _1063: x0 => x0.disabled,
      _1064: (x0,x1) => { x0.disabled = x1 },
      _1066: (x0,x1) => { x0.placeholder = x1 },
      _1068: (x0,x1) => { x0.name = x1 },
      _1069: (x0,x1) => { x0.autocomplete = x1 },
      _1071: x0 => x0.selectionDirection,
      _1072: x0 => x0.selectionStart,
      _1074: x0 => x0.selectionEnd,
      _1077: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _1078: (x0,x1) => x0.add(x1),
      _1081: (x0,x1) => { x0.noValidate = x1 },
      _1082: (x0,x1) => { x0.method = x1 },
      _1083: (x0,x1) => { x0.action = x1 },
      _1108: x0 => x0.orientation,
      _1109: x0 => x0.width,
      _1110: x0 => x0.height,
      _1111: (x0,x1) => x0.lock(x1),
      _1130: x0 => new ResizeObserver(x0),
      _1133: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1133(f,arguments.length,x0,x1) }),
      _1141: x0 => x0.length,
      _1142: x0 => x0.iterator,
      _1143: x0 => x0.Segmenter,
      _1144: x0 => x0.v8BreakIterator,
      _1145: (x0,x1) => new Intl.Segmenter(x0,x1),
      _1148: x0 => x0.language,
      _1149: x0 => x0.script,
      _1150: x0 => x0.region,
      _1168: x0 => x0.done,
      _1169: x0 => x0.value,
      _1170: x0 => x0.index,
      _1174: (x0,x1) => new Intl.v8BreakIterator(x0,x1),
      _1175: (x0,x1) => x0.adoptText(x1),
      _1176: x0 => x0.first(),
      _1177: x0 => x0.next(),
      _1178: x0 => x0.current(),
      _1191: x0 => x0.hostElement,
      _1192: x0 => x0.viewConstraints,
      _1195: x0 => x0.maxHeight,
      _1196: x0 => x0.maxWidth,
      _1197: x0 => x0.minHeight,
      _1198: x0 => x0.minWidth,
      _1199: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1199(f,arguments.length,x0) }),
      _1200: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1200(f,arguments.length,x0) }),
      _1201: (x0,x1) => ({addView: x0,removeView: x1}),
      _1204: x0 => x0.loader,
      _1205: () => globalThis._flutter,
      _1206: (x0,x1) => x0.didCreateEngineInitializer(x1),
      _1207: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1207(f,arguments.length,x0) }),
      _1208: (module,f) => finalizeWrapper(f, function() { return module.exports._1208(f,arguments.length) }),
      _1209: (x0,x1) => ({initializeEngine: x0,autoStart: x1}),
      _1212: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1212(f,arguments.length,x0) }),
      _1213: x0 => ({runApp: x0}),
      _1215: (x0,x1,x2) => x0.call(x1,x2),
      _1216: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1216(f,arguments.length,x0,x1) }),
      _1217: x0 => new Promise(x0),
      _1218: x0 => x0.length,
      _1219: () => globalThis.window.ImageDecoder,
      _1220: x0 => x0.tracks,
      _1222: x0 => x0.completed,
      _1224: x0 => x0.image,
      _1230: x0 => x0.displayWidth,
      _1231: x0 => x0.displayHeight,
      _1232: x0 => x0.duration,
      _1235: x0 => x0.ready,
      _1236: x0 => x0.selectedTrack,
      _1237: x0 => x0.repetitionCount,
      _1238: x0 => x0.frameCount,
      _1286: (x0,x1) => x0.createElement(x1),
      _1292: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1294: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _1295: (x0,x1,x2,x3) => x0.removeEventListener(x1,x2,x3),
      _1296: (x0,x1) => x0.createElement(x1),
      _1298: (x0,x1) => x0.removeAttribute(x1),
      _1303: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1314: x0 => x0.toArray(),
      _1315: x0 => x0.toUint8Array(),
      _1316: x0 => ({serverTimestamps: x0}),
      _1317: x0 => ({source: x0}),
      _1318: x0 => ({merge: x0}),
      _1320: x0 => new firebase_firestore.FieldPath(x0),
      _1321: (x0,x1) => new firebase_firestore.FieldPath(x0,x1),
      _1322: (x0,x1,x2) => new firebase_firestore.FieldPath(x0,x1,x2),
      _1323: (x0,x1,x2,x3) => new firebase_firestore.FieldPath(x0,x1,x2,x3),
      _1324: (x0,x1,x2,x3,x4) => new firebase_firestore.FieldPath(x0,x1,x2,x3,x4),
      _1325: (x0,x1,x2,x3,x4,x5) => new firebase_firestore.FieldPath(x0,x1,x2,x3,x4,x5),
      _1326: (x0,x1,x2,x3,x4,x5,x6) => new firebase_firestore.FieldPath(x0,x1,x2,x3,x4,x5,x6),
      _1327: (x0,x1,x2,x3,x4,x5,x6,x7) => new firebase_firestore.FieldPath(x0,x1,x2,x3,x4,x5,x6,x7),
      _1328: (x0,x1,x2,x3,x4,x5,x6,x7,x8) => new firebase_firestore.FieldPath(x0,x1,x2,x3,x4,x5,x6,x7,x8),
      _1329: (x0,x1,x2,x3,x4,x5,x6,x7,x8,x9) => new firebase_firestore.FieldPath(x0,x1,x2,x3,x4,x5,x6,x7,x8,x9),
      _1330: () => globalThis.firebase_firestore.documentId(),
      _1331: (x0,x1) => new firebase_firestore.GeoPoint(x0,x1),
      _1332: x0 => globalThis.firebase_firestore.vector(x0),
      _1333: x0 => globalThis.firebase_firestore.Bytes.fromUint8Array(x0),
      _1335: (x0,x1) => globalThis.firebase_firestore.collection(x0,x1),
      _1337: (x0,x1) => globalThis.firebase_firestore.doc(x0,x1),
      _1369: x0 => globalThis.firebase_firestore.getDoc(x0),
      _1370: x0 => globalThis.firebase_firestore.getDocFromServer(x0),
      _1371: x0 => globalThis.firebase_firestore.getDocFromCache(x0),
      _1377: (x0,x1,x2) => globalThis.firebase_firestore.setDoc(x0,x1,x2),
      _1378: (x0,x1) => globalThis.firebase_firestore.setDoc(x0,x1),
      _1379: (x0,x1) => globalThis.firebase_firestore.query(x0,x1),
      _1380: x0 => globalThis.firebase_firestore.getDocs(x0),
      _1381: x0 => globalThis.firebase_firestore.getDocsFromServer(x0),
      _1382: x0 => globalThis.firebase_firestore.getDocsFromCache(x0),
      _1383: x0 => globalThis.firebase_firestore.limit(x0),
      _1384: x0 => globalThis.firebase_firestore.limitToLast(x0),
      _1387: (x0,x1) => globalThis.firebase_firestore.orderBy(x0,x1),
      _1389: (x0,x1,x2) => globalThis.firebase_firestore.where(x0,x1,x2),
      _1394: (x0,x1) => x0.data(x1),
      _1398: x0 => x0.docChanges(),
      _1407: x0 => globalThis.firebase_firestore.increment(x0),
      _1416: (x0,x1) => globalThis.firebase_firestore.getFirestore(x0,x1),
      _1418: x0 => globalThis.firebase_firestore.Timestamp.fromMillis(x0),
      _1419: (module,f) => finalizeWrapper(f, function() { return module.exports._1419(f,arguments.length) }),
      _1552: () => globalThis.firebase_firestore.or,
      _1553: () => globalThis.firebase_firestore.and,
      _1567: x0 => x0.path,
      _1570: () => globalThis.firebase_firestore.GeoPoint,
      _1571: x0 => x0.latitude,
      _1572: x0 => x0.longitude,
      _1574: () => globalThis.firebase_firestore.VectorValue,
      _1575: () => globalThis.firebase_firestore.Bytes,
      _1578: x0 => x0.type,
      _1580: x0 => x0.doc,
      _1582: x0 => x0.oldIndex,
      _1584: x0 => x0.newIndex,
      _1586: () => globalThis.firebase_firestore.DocumentReference,
      _1590: x0 => x0.path,
      _1599: x0 => x0.metadata,
      _1600: x0 => x0.ref,
      _1605: x0 => x0.docs,
      _1607: x0 => x0.metadata,
      _1612: () => globalThis.firebase_firestore.Timestamp,
      _1613: x0 => x0.seconds,
      _1614: x0 => x0.nanoseconds,
      _1650: x0 => x0.hasPendingWrites,
      _1652: x0 => x0.fromCache,
      _1659: x0 => x0.source,
      _1664: () => globalThis.firebase_firestore.startAfter,
      _1665: () => globalThis.firebase_firestore.startAt,
      _1666: () => globalThis.firebase_firestore.endBefore,
      _1667: () => globalThis.firebase_firestore.endAt,
      _1694: x0 => x0.load(),
      _1695: x0 => x0.play(),
      _1696: x0 => x0.pause(),
      _1700: (x0,x1) => x0.start(x1),
      _1701: (x0,x1) => x0.end(x1),
      _1702: x0 => x0.decode(),
      _1703: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1704: (x0,x1,x2) => x0.setRequestHeader(x1,x2),
      _1705: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1705(f,arguments.length,x0) }),
      _1706: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1706(f,arguments.length,x0) }),
      _1707: x0 => x0.send(),
      _1708: () => new XMLHttpRequest(),
      _1709: (x0,x1) => x0.getItem(x1),
      _1711: (x0,x1,x2) => x0.setItem(x1,x2),
      _1713: (x0,x1,x2,x3,x4,x5,x6,x7) => ({apiKey: x0,authDomain: x1,databaseURL: x2,projectId: x3,storageBucket: x4,messagingSenderId: x5,measurementId: x6,appId: x7}),
      _1714: (x0,x1) => globalThis.firebase_core.initializeApp(x0,x1),
      _1715: x0 => globalThis.firebase_core.getApp(x0),
      _1716: () => globalThis.firebase_core.getApp(),
      _1717: (x0,x1,x2) => globalThis.firebase_core.registerVersion(x0,x1,x2),
      _1719: () => globalThis.firebase_core.SDK_VERSION,
      _1725: x0 => x0.apiKey,
      _1727: x0 => x0.authDomain,
      _1729: x0 => x0.databaseURL,
      _1731: x0 => x0.projectId,
      _1733: x0 => x0.storageBucket,
      _1735: x0 => x0.messagingSenderId,
      _1737: x0 => x0.measurementId,
      _1739: x0 => x0.appId,
      _1741: x0 => x0.name,
      _1742: x0 => x0.options,
      _1743: (x0,x1) => x0.debug(x1),
      _1744: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1744(f,arguments.length,x0) }),
      _1745: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1745(f,arguments.length,x0,x1) }),
      _1746: (x0,x1) => ({createScript: x0,createScriptURL: x1}),
      _1747: (x0,x1,x2) => x0.createPolicy(x1,x2),
      _1748: (x0,x1) => x0.createScriptURL(x1),
      _1749: (x0,x1,x2) => x0.createScript(x1,x2),
      _1750: (x0,x1) => x0.appendChild(x1),
      _1751: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1751(f,arguments.length,x0) }),
      _1753: Date.now,
      _1755: s => new Date(s * 1000).getTimezoneOffset() * 60,
      _1756: s => {
        if (!/^\s*[+-]?(?:Infinity|NaN|(?:\.\d+|\d+(?:\.\d*)?)(?:[eE][+-]?\d+)?)\s*$/.test(s)) {
          return NaN;
        }
        return parseFloat(s);
      },
      _1757: () => new Error().stack,
      _1758: () => typeof dartUseDateNowForTicks !== "undefined",
      _1759: () => 1000 * performance.now(),
      _1760: () => Date.now(),
      _1761: () => {
        // On browsers return `globalThis.location.href`
        if (globalThis.location != null) {
          return globalThis.location.href;
        }
        return null;
      },
      _1762: () => {
        return typeof process != "undefined" &&
               Object.prototype.toString.call(process) == "[object process]" &&
               process.platform == "win32"
      },
      _1763: () => new WeakMap(),
      _1764: (map, o) => map.get(o),
      _1765: (map, o, v) => map.set(o, v),
      _1766: (exn) => exn.toString(),
      _1767: (exn) => exn.stack,
      _1768: (exn) => {
        let stackString = exn.toString();
        let frames = stackString.split('\n');
        let drop = 2;
        if (frames[0] === 'Error') {
            drop += 1;
        }
        return frames.slice(drop).join('\n');
      },
      _1769: x0 => new WeakRef(x0),
      _1770: x0 => x0.deref(),
      _1777: () => globalThis.WeakRef,
      _1780: s => JSON.stringify(s),
      _1781: s => printToConsole(s),
      _1782: (o, p, r) => o.replaceAll(p, () => r),
      _1783: (o, p, r) => o.replace(p, () => r),
      _1784: Function.prototype.call.bind(String.prototype.toLowerCase),
      _1785: s => s.toUpperCase(),
      _1786: s => s.trim(),
      _1787: s => s.trimLeft(),
      _1788: s => s.trimRight(),
      _1789: (string, times) => string.repeat(times),
      _1790: Function.prototype.call.bind(String.prototype.indexOf),
      _1791: (s, p, i) => s.lastIndexOf(p, i),
      _1792: (string, token) => string.split(token),
      _1793: Object.is,
      _1797: (o, c) => o instanceof c,
      _1798: o => Object.keys(o),
      _1828: x0 => new Array(x0),
      _1830: x0 => x0.length,
      _1832: (x0,x1) => x0[x1],
      _1833: (x0,x1,x2) => { x0[x1] = x2 },
      _1836: (x0,x1,x2) => new DataView(x0,x1,x2),
      _1838: x0 => new Int8Array(x0),
      _1839: (x0,x1,x2) => new Uint8Array(x0,x1,x2),
      _1841: x0 => new Uint8ClampedArray(x0),
      _1843: x0 => new Int16Array(x0),
      _1845: x0 => new Uint16Array(x0),
      _1847: x0 => new Int32Array(x0),
      _1849: x0 => new Uint32Array(x0),
      _1851: x0 => new Float32Array(x0),
      _1853: x0 => new Float64Array(x0),
      _1877: x0 => x0.random(),
      _1880: () => globalThis.Math,
      _1893: (ms, c) =>
      setTimeout(() => dartInstance.exports.$invokeCallback(c),ms),
      _1894: (handle) => clearTimeout(handle),
      _1895: (ms, c) =>
      setInterval(() => dartInstance.exports.$invokeCallback(c), ms),
      _1896: (handle) => clearInterval(handle),
      _1897: (c) =>
      queueMicrotask(() => dartInstance.exports.$invokeCallback(c)),
      _1898: () => Date.now(),
      _1899: (s, m) => {
        try {
          return new RegExp(s, m);
        } catch (e) {
          return String(e);
        }
      },
      _1900: (x0,x1) => x0.exec(x1),
      _1901: (x0,x1) => x0.test(x1),
      _1902: x0 => x0.pop(),
      _1904: o => o === undefined,
      _1906: o => typeof o === 'function' && o[jsWrappedDartFunctionSymbol] === true,
      _1908: o => {
        const proto = Object.getPrototypeOf(o);
        return proto === Object.prototype || proto === null;
      },
      _1909: o => o instanceof RegExp,
      _1910: (l, r) => l === r,
      _1911: o => o,
      _1912: o => o,
      _1913: o => o,
      _1914: b => !!b,
      _1915: o => o.length,
      _1917: (o, i) => o[i],
      _1918: f => f.dartFunction,
      _1919: () => ({}),
      _1920: () => [],
      _1922: () => globalThis,
      _1923: (constructor, args) => {
        const factoryFunction = constructor.bind.apply(
            constructor, [null, ...args]);
        return new factoryFunction();
      },
      _1925: (o, p) => o[p],
      _1926: (o, p, v) => o[p] = v,
      _1927: (o, m, a) => o[m].apply(o, a),
      _1929: o => String(o),
      _1930: (p, s, f) => p.then(s, (e) => f(e, e === undefined)),
      _1931: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1931(f,arguments.length,x0) }),
      _1932: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1932(f,arguments.length,x0,x1) }),
      _1933: o => {
        if (o === undefined) return 1;
        var type = typeof o;
        if (type === 'boolean') return 2;
        if (type === 'number') return 3;
        if (type === 'string') return 4;
        if (o instanceof Array) return 5;
        if (ArrayBuffer.isView(o)) {
          if (o instanceof Int8Array) return 6;
          if (o instanceof Uint8Array) return 7;
          if (o instanceof Uint8ClampedArray) return 8;
          if (o instanceof Int16Array) return 9;
          if (o instanceof Uint16Array) return 10;
          if (o instanceof Int32Array) return 11;
          if (o instanceof Uint32Array) return 12;
          if (o instanceof Float32Array) return 13;
          if (o instanceof Float64Array) return 14;
          if (o instanceof DataView) return 15;
        }
        if (o instanceof ArrayBuffer) return 16;
        // Feature check for `SharedArrayBuffer` before doing a type-check.
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
            return 17;
        }
        if (o instanceof Promise) return 18;
        return 19;
      },
      _1934: o => [o],
      _1935: (o0, o1) => [o0, o1],
      _1936: (o0, o1, o2) => [o0, o1, o2],
      _1937: (o0, o1, o2, o3) => [o0, o1, o2, o3],
      _1938: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI8ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1939: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI8ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1942: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1943: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1944: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1945: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1946: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF64ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1947: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF64ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1948: x0 => new ArrayBuffer(x0),
      _1949: s => {
        if (/[[\]{}()*+?.\\^$|]/.test(s)) {
            s = s.replace(/[[\]{}()*+?.\\^$|]/g, '\\$&');
        }
        return s;
      },
      _1951: x0 => x0.index,
      _1953: x0 => x0.flags,
      _1954: x0 => x0.multiline,
      _1955: x0 => x0.ignoreCase,
      _1956: x0 => x0.unicode,
      _1957: x0 => x0.dotAll,
      _1958: (x0,x1) => { x0.lastIndex = x1 },
      _1959: (o, p) => p in o,
      _1960: (o, p) => o[p],
      _1961: (o, p, v) => o[p] = v,
      _1962: (o, p) => delete o[p],
      _1971: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1971(f,arguments.length,x0) }),
      _1977: () => new AbortController(),
      _1978: x0 => x0.abort(),
      _1979: (x0,x1,x2,x3,x4,x5) => ({method: x0,headers: x1,body: x2,credentials: x3,redirect: x4,signal: x5}),
      _1980: (x0,x1) => globalThis.fetch(x0,x1),
      _1981: (x0,x1) => x0.get(x1),
      _1982: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1982(f,arguments.length,x0,x1,x2) }),
      _1983: (x0,x1) => x0.forEach(x1),
      _1984: x0 => x0.getReader(),
      _1985: x0 => x0.cancel(),
      _1986: x0 => x0.read(),
      _1990: (x0,x1) => x0.key(x1),
      _1991: x0 => x0.trustedTypes,
      _1992: (x0,x1) => { x0.text = x1 },
      _1993: o => o instanceof Array,
      _1998: a => a.pop(),
      _1999: (a, i) => a.splice(i, 1),
      _2000: (a, s) => a.join(s),
      _2001: (a, s, e) => a.slice(s, e),
      _2003: (a, b) => a == b ? 0 : (a > b ? 1 : -1),
      _2004: a => a.length,
      _2006: (a, i) => a[i],
      _2007: (a, i, v) => a[i] = v,
      _2009: o => {
        if (o instanceof ArrayBuffer) return 0;
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
          return 1;
        }
        return 2;
      },
      _2010: (o, offsetInBytes, lengthInBytes) => {
        var dst = new ArrayBuffer(lengthInBytes);
        new Uint8Array(dst).set(new Uint8Array(o, offsetInBytes, lengthInBytes));
        return new DataView(dst);
      },
      _2012: o => o instanceof Uint8Array,
      _2013: (o, start, length) => new Uint8Array(o.buffer, o.byteOffset + start, length),
      _2014: o => o instanceof Int8Array,
      _2015: (o, start, length) => new Int8Array(o.buffer, o.byteOffset + start, length),
      _2016: o => o instanceof Uint8ClampedArray,
      _2017: (o, start, length) => new Uint8ClampedArray(o.buffer, o.byteOffset + start, length),
      _2018: o => o instanceof Uint16Array,
      _2019: (o, start, length) => new Uint16Array(o.buffer, o.byteOffset + start, length),
      _2020: o => o instanceof Int16Array,
      _2021: (o, start, length) => new Int16Array(o.buffer, o.byteOffset + start, length),
      _2022: o => o instanceof Uint32Array,
      _2023: (o, start, length) => new Uint32Array(o.buffer, o.byteOffset + start, length),
      _2024: o => o instanceof Int32Array,
      _2025: (o, start, length) => new Int32Array(o.buffer, o.byteOffset + start, length),
      _2027: (o, start, length) => new BigInt64Array(o.buffer, o.byteOffset + start, length),
      _2028: o => o instanceof Float32Array,
      _2029: (o, start, length) => new Float32Array(o.buffer, o.byteOffset + start, length),
      _2030: o => o instanceof Float64Array,
      _2031: (o, start, length) => new Float64Array(o.buffer, o.byteOffset + start, length),
      _2032: (t, s) => t.set(s),
      _2034: (o) => new DataView(o.buffer, o.byteOffset, o.byteLength),
      _2036: o => o.buffer,
      _2037: o => o.byteOffset,
      _2038: Function.prototype.call.bind(Object.getOwnPropertyDescriptor(DataView.prototype, 'byteLength').get),
      _2039: (b, o) => new DataView(b, o),
      _2040: (b, o, l) => new DataView(b, o, l),
      _2041: Function.prototype.call.bind(DataView.prototype.getUint8),
      _2042: Function.prototype.call.bind(DataView.prototype.setUint8),
      _2043: Function.prototype.call.bind(DataView.prototype.getInt8),
      _2044: Function.prototype.call.bind(DataView.prototype.setInt8),
      _2045: Function.prototype.call.bind(DataView.prototype.getUint16),
      _2046: Function.prototype.call.bind(DataView.prototype.setUint16),
      _2047: Function.prototype.call.bind(DataView.prototype.getInt16),
      _2048: Function.prototype.call.bind(DataView.prototype.setInt16),
      _2049: Function.prototype.call.bind(DataView.prototype.getUint32),
      _2050: Function.prototype.call.bind(DataView.prototype.setUint32),
      _2051: Function.prototype.call.bind(DataView.prototype.getInt32),
      _2052: Function.prototype.call.bind(DataView.prototype.setInt32),
      _2055: Function.prototype.call.bind(DataView.prototype.getBigInt64),
      _2056: Function.prototype.call.bind(DataView.prototype.setBigInt64),
      _2057: Function.prototype.call.bind(DataView.prototype.getFloat32),
      _2058: Function.prototype.call.bind(DataView.prototype.setFloat32),
      _2059: Function.prototype.call.bind(DataView.prototype.getFloat64),
      _2060: Function.prototype.call.bind(DataView.prototype.setFloat64),
      _2061: Function.prototype.call.bind(Number.prototype.toString),
      _2062: Function.prototype.call.bind(BigInt.prototype.toString),
      _2063: Function.prototype.call.bind(Number.prototype.toString),
      _2064: (d, digits) => d.toFixed(digits),
      _2077: () => globalThis.document,
      _2083: (x0,x1) => { x0.height = x1 },
      _2085: (x0,x1) => { x0.width = x1 },
      _2087: (x0,x1) => { x0.pointerEvents = x1 },
      _2096: x0 => x0.style,
      _2099: x0 => x0.src,
      _2100: (x0,x1) => { x0.src = x1 },
      _2101: x0 => x0.naturalWidth,
      _2102: x0 => x0.naturalHeight,
      _2118: x0 => x0.status,
      _2119: (x0,x1) => { x0.responseType = x1 },
      _2121: x0 => x0.response,
      _2248: x0 => x0.style,
      _2820: x0 => x0.videoWidth,
      _2821: x0 => x0.videoHeight,
      _2825: (x0,x1) => { x0.playsInline = x1 },
      _2851: x0 => x0.error,
      _2853: (x0,x1) => { x0.src = x1 },
      _2862: x0 => x0.buffered,
      _2865: x0 => x0.currentTime,
      _2866: (x0,x1) => { x0.currentTime = x1 },
      _2867: x0 => x0.duration,
      _2872: (x0,x1) => { x0.playbackRate = x1 },
      _2879: (x0,x1) => { x0.autoplay = x1 },
      _2881: (x0,x1) => { x0.loop = x1 },
      _2883: (x0,x1) => { x0.controls = x1 },
      _2885: (x0,x1) => { x0.volume = x1 },
      _2887: (x0,x1) => { x0.muted = x1 },
      _2902: x0 => x0.code,
      _2903: x0 => x0.message,
      _2976: x0 => x0.length,
      _3482: (x0,x1) => { x0.type = x1 },
      _3490: (x0,x1) => { x0.crossOrigin = x1 },
      _3492: (x0,x1) => { x0.text = x1 },
      _3949: () => globalThis.window,
      _4011: x0 => x0.navigator,
      _4273: x0 => x0.trustedTypes,
      _4274: x0 => x0.sessionStorage,
      _4275: x0 => x0.localStorage,
      _4400: x0 => x0.userAgent,
      _4608: x0 => x0.length,
      _6553: x0 => x0.signal,
      _6627: () => globalThis.document,
      _6711: x0 => x0.head,
      _7043: (x0,x1) => { x0.id = x1 },
      _8389: x0 => x0.value,
      _8391: x0 => x0.done,
      _9093: x0 => x0.url,
      _9095: x0 => x0.status,
      _9097: x0 => x0.statusText,
      _9098: x0 => x0.headers,
      _9099: x0 => x0.body,
      _11227: (x0,x1) => { x0.border = x1 },
      _11669: (x0,x1) => { x0.height = x1 },
      _12359: (x0,x1) => { x0.width = x1 },
      _12727: x0 => x0.name,
      _12728: x0 => x0.message,
      _13445: () => globalThis.console,
      _13473: x0 => x0.name,
      _13474: x0 => x0.message,
      _13475: x0 => x0.code,

    };

    const baseImports = {
      dart2wasm: dart2wasm,
      Math: Math,
      Date: Date,
      Object: Object,
      Array: Array,
      Reflect: Reflect,
      WebAssembly: {
        JSTag: WebAssembly.JSTag,
      },
      "": new Proxy({}, { get(_, prop) { return prop; } }),

    };

    const jsStringPolyfill = {
      "charCodeAt": (s, i) => s.charCodeAt(i),
      "compare": (s1, s2) => {
        if (s1 < s2) return -1;
        if (s1 > s2) return 1;
        return 0;
      },
      "concat": (s1, s2) => s1 + s2,
      "equals": (s1, s2) => s1 === s2,
      "fromCharCode": (i) => String.fromCharCode(i),
      "length": (s) => s.length,
      "substring": (s, a, b) => s.substring(a, b),
      "fromCharCodeArray": (a, start, end) => {
        if (end <= start) return '';

        const read = dartInstance.exports.$wasmI16ArrayGet;
        let result = '';
        let index = start;
        const chunkLength = Math.min(end - index, 500);
        let array = new Array(chunkLength);
        while (index < end) {
          const newChunkLength = Math.min(end - index, 500);
          for (let i = 0; i < newChunkLength; i++) {
            array[i] = read(a, index++);
          }
          if (newChunkLength < chunkLength) {
            array = array.slice(0, newChunkLength);
          }
          result += String.fromCharCode(...array);
        }
        return result;
      },
      "intoCharCodeArray": (s, a, start) => {
        if (s === '') return 0;

        const write = dartInstance.exports.$wasmI16ArraySet;
        for (var i = 0; i < s.length; ++i) {
          write(a, start++, s.charCodeAt(i));
        }
        return s.length;
      },
      "test": (s) => typeof s == "string",
    };


    

    dartInstance = await WebAssembly.instantiate(this.module, {
      ...baseImports,
      ...additionalImports,
      
      "wasm:js-string": jsStringPolyfill,
    });
    dartInstance.exports.$setThisModule(dartInstance);

    return new InstantiatedApp(this, dartInstance);
  }
}

class InstantiatedApp {
  constructor(compiledApp, instantiatedModule) {
    this.compiledApp = compiledApp;
    this.instantiatedModule = instantiatedModule;
  }

  // Call the main function with the given arguments.
  invokeMain(...args) {
    this.instantiatedModule.exports.$invokeMain(args);
  }
}
