name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Dart 🛠️
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Activate Jaspr CLI 📦
        run: dart pub global activate jaspr_cli

      - name: Install dependencies 📦
        working-directory: jaspr_site
        run: dart pub get

      - name: Build Jaspr site 🏗️
        working-directory: jaspr_site
        run: dart pub global run jaspr_cli:jaspr build --sitemap-domain=https://muhammed-adel.web.app

      - name: Deploy to Firebase Hosting 🚀
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MY_WEBSITE_BF9E6 }}"
          projectId: my-website-bf9e6
          channelId: live
